-- ORACLE redirect to the desired room
ALTER SESSION SET CONTAINER = XEPDB1;

-- Route all subsequent database operations to our dedicated application schema telco_dev
ALTER SESSION SET CURRENT_SCHEMA = telco_dev;

CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE NUMBER(10, 2) NOT NULL,
    DATA_LIMIT NUMBER NOT NULL,
    MINUTE_LIMIT NUMBER NOT NULL,
    SMS_LIMIT NUMBER NOT NULL
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    CITY VARCHAR2(50),
    SIGNUP_DATE DATE NOT NULL,
    TARIFF_ID NUMBER,
    CONSTRAINT fk_customer_tariff FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

-- B-Tree İndexs
CREATE INDEX idx_customers_city ON CUSTOMERS(CITY);
CREATE INDEX idx_customers_signup ON CUSTOMERS(SIGNUP_DATE);
CREATE INDEX idx_customers_tariff ON CUSTOMERS(TARIFF_ID);


CREATE TABLE MONTHLY_STATS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    DATA_USAGE NUMBER(10, 2) DEFAULT 0,
    MINUTE_USAGE NUMBER DEFAULT 0,
    SMS_USAGE NUMBER DEFAULT 0,
    PAYMENT_STATUS VARCHAR2(20),
    CONSTRAINT fk_stats_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Foreign Key B-Tree index to speed up JOIN operations
CREATE INDEX idx_monthly_stats_cust ON MONTHLY_STATS(CUSTOMER_ID);

-- Oracle special BITMAP İndex
CREATE BITMAP INDEX idx_payment_status ON MONTHLY_STATS(PAYMENT_STATUS);