version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: i2i_oracle_db
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - APP_USER=${APP_USER}                   
      - APP_USER_PASSWORD=${APP_USER_PASSWORD}    
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-scripts:/container-entrypoint-initdb.d
    restart: always

volumes:
  oracle-data: